name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  vim:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vim-version: ['v9.1.0000', 'v9.2.0000']
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.vim-version }}
      - run: make check

  scala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
        with:
          apps: scalac:3.9.0
      - run: make test-scala
